### ISSUE TITLE
Events system rework

### ISSUE THREAD

**Issue by James-Mart** [gofractally/psibase#236]
Need a spec for the new events system with simpler syntax, less boilerplate.

This is in the "system-app" category because it is a breaking change that will affect how all system apps are written.
```[tasklist]
### Tasks
- [ ] https://github.com/gofractally/psibase/issues/384
- [ ] https://github.com/gofractally/psibase/issues/228
- [ ] Subtask: delete merkle events
- [ ] https://github.com/gofractally/psibase/issues/457
- [ ] Subtask: write new developer event definition / emission interface
- [ ] Subtask: use new interface in all system/user applications
- [ ] Subtask: delete old event definition / emission interface
```

**Comment by James-Mart** [comment]
Closing in favor of the new event system introduced here
https://github.com/gofractally/psibase/pull/691
