### ISSUE TITLE
Automatic ARM docker image builds

### ISSUE THREAD

**Issue by James-Mart** [gofractally/psibase#411]
Test m1 builds here
macstadium.com
```[tasklist]
### Tasks
- [ ] https://github.com/gofractally/psibase/issues/471
- [x] Write images that work for arm builds
- [ ] https://github.com/github/roadmap/issues/528
- [x] Add arm builds to CI/CD
```

We are waiting on github to add mac runners in order to automatically build images and store them in ghcr, because qemu emulation is too slow. The github runners kill the build after 6 hours.

**Comment by James-Mart** [comment]
## Update

The m1 runners were added to github, however, they [do not have Docker](https://github.com/actions/runner-images/blob/main/images/macos/macos-13-arm64-Readme.md) installed on them.

Furthermore, it is not possible, or at least not trivial, to add Docker to the image when I only have CLI access (since Docker Engine on Mac can only be installed through Docker Desktop which requires GUI interaction).

Therefore, this task is now roadblocked until linux arm64 runners are added, which is [scheduled for January 2024](https://github.blog/changelog/2023-10-30-accelerate-your-ci-cd-with-arm-based-hosted-runners-in-github-actions/).
