### ISSUE TITLE
Node synchronization - Replay

### ISSUE THREAD

**Issue by James-Mart** [gofractally/psibase#430]
## Description

Tasks necessary for synchronizing nodes from peers via replay

```[tasklist]
### Tasks
- [ ] Subtask: create specification
- [ ] Subtask: support replay
- [ ] https://github.com/gofractally/psibase/issues/234
```

**Comment by James-Mart** [comment]
Status here @swatanabe ? Replay is sufficiently complete, no?
