### ISSUE TITLE
Psibase release strategy - phase 1

### ISSUE THREAD

**Issue by James-Mart** [gofractally/psibase#450]
```[tasklist]
### Tasks
- [x] Subtask: Create prioritized backlog
- [x] Subtask: Create release branching strategy
- [x] Subtask: Add version information to all Psibase CLI tools
- [x] Subtask: Update CI/CD to automate release draft based on new tags
- [x] Subtask: Update image-builders to pull binaries from a specific release instead of rolling-release
- [x] Subtask: Fix the generated release notes to look better
- [x] Subtask: Add separate workflow to post to telegram on publication of new release
- [x] Subtask: Update CI/CD to automatically trigger image-builders cli.yml workflow
- [x] Subtask: Look into tagging PRs with labels from linked issues
```

**Comment by James-Mart** [comment]
Release branching strategy document can be found [here](https://www.notion.so/psinq/Release-strategy-4c3558255b15453381e4c75beaf6468c).

**Comment by James-Mart** [comment]
Version information added to CLI tools in [this pr](https://github.com/gofractally/psibase/pull/475).

**Comment by James-Mart** [comment]
CI/CD updated in [this pr](https://github.com/gofractally/psibase/pull/474).

**Comment by James-Mart** [comment]
`image-builders` now pulls artifacts from a release instead of rolling release as of [this pr](https://github.com/gofractally/image-builders/pull/10).
