### ISSUE TITLE
Node synchronization - Snapshots

### ISSUE THREAD

**Issue by James-Mart** [gofractally/psibase#464]
Support the ability for IPs to create state snapshots from which others can synchronize.

This should probably come after large file support, and then we can reuse the same mechanisms as large file support for snapshot distribution.

```[tasklist]
### Tasks
- [ ] Subtask: create specification
- [ ] Subtask: Add snapshot generation support
- [ ] Subtask: Support snapshot download from peer
- [ ] Subtask: Support starting from snapshot
```
