### ISSUE TITLE
Authenticated queries

### ISSUE THREAD

**Issue by James-Mart** [gofractally/psibase#673]
# Background and goals

We want for all interactions with a psibase node to be authenticated, including subjective interactions (interactions with a particular node). This allows for billing relationships between users and particular full nodes, which helps pay for network infrastructure and avoids nodes being required to subsidize user activity that cannot be billed objectively (such as failed transactions, RPC queries, etc.). It also allows RPC services to permission requests based on the querier.

# Client-side overview

### Cookie

We need to set a cookie on the third-party app domain so that requests made to that third-party app with the fetch API (and `<img>` tags and other primitives that use fetch underneath) will automatically be authenticated.

### Bearer token

When the supervisor (framed in a client app) makes requests to the server (e.g. fetching plugins), it must also be authenticated. It cannot use a cookie, because it's making requests to many different subdomains. Instead, it must use a bearer token attached as a header on the request.

# Server side overview

## Transact service

The transact RPC service will define a `POST /login` endpoint that takes a packed transaction as a body, signed by the user who is logging in. See [the docs](https://github.com/gofractally/psibase/blob/main/doc/psidk/src/default-apps/transact.md#login) for details on the login endpoint.

This endpoint essentially generates a query token and provides it in a response. The token can be used in subsequent requests to authenticate a user.

# Diagrams

## Sequence Diagram

This is specifically for the flow wherein the user is redirected to the Accounts app.

```mermaid
sequenceDiagram
autonumber

title Connecting new user

participant au as accounts UI
participant a as accounts
participant h as host:auth
participant t as transact
participant c as host:common

au->>a: login_direct
  a->>h: set-logged-in-user(user, app)

  alt if no token for user-app exists
    h->>t: get-query-token
	activate t
	note over t: (posts to server)
    t-->>h: <return token>
    deactivate t
    note over h: store user-app-token mapping
  end

  h->>c: post query token (calls set-cookie)
  alt on subsequent do_post/do_get
    note over a,c: Look up and attach the correct token
    c->>h: get-active-query-token(app)
      h->>a: get-current-user
      a-->>h: return <user>
    note over h: look up <user>-<app>
    h-->>c: return <token>
    
  end
a-->>au: return
```

# Related issues
1. #1274
1. #1275
1. #1281 
2. #1360 
3. #1361

# Subtasks

- [x] Accounts app facilitate getting query tokens: #1250 
- [x] Server support for setting auth cookies #1291 
- [x] Enable authenticated queries from third-party root apps (uses auth cookies): #1342
- [x] Enable authenticated queries for plugin get/post requests: #1347 
- [x] Enable authenticated queries for switching users: #1347 
- [x] Enable authenticated queries for host plugin loading: #1365
- [x] Handle logging out (clear the HttpOnly cookie): #1347

**Comment by swatanabe** [comment]
> `domain=callerapp.rootdomain.com`

This causes the cookie to be sent for subdomains of callerapp.rootdomain.com. I think we either want `domain=rootdomain.com` (for a single global cookie) or no domain (which will not send the cookie to subdomains).
