### ISSUE TITLE
Admin app rework

### ISSUE THREAD

**Issue by James-Mart** [gofractally/psibase#742]
# Description

The admin app needs to be revamped for increased usability and functionality.
Primary use-cases for the app:
1. Creating a new psibase network
2. Joining an existing psibase network
3. Configuring a node that has already joined a network
4. Monitoring a node that has already joined a network

This task is primarily focused on the first 3 use-cases, as monitoring is lower priority than network creation/joining at this stage. 

# Tasks

```[tasklist]
- [x] By default, show the "Join a Network" wizard if psinode has no existing connection to any network
- [x] Allow access to the "Create a Network" wizard if the user does not intend to join any existing network
- [x] Rework single configuration page from into a horizontally navigable experience
- [x] Rework logs page for easier filtering
- [x] Add a new home page to the Admin app for when the app is run while connected to a network. This home page shows some basic statistics about the network, or potentially about the node.
- [ ] Add missing configurations, mainly for key management and TLS certificate management
```
-----------------------

@Velua feel free to add any notes or items that I am not remembering from our conversation

**Comment by Velua** [comment]
## Paths
- Join network or create network
- - Upgrade to block producing node
Create network should immediately resolve to block producing form, join network won't. 
**Connection to the network is done with a single node, multiple URLs not needed**

## Peers page
- Should be allowed to terminate connections
- Switch between transient and persistent connections. 
- Wishlist: Show ping for connections
- Wishlist: See connection account name

## Logs page
- Should be able to toggle between remembering the last 25 logs and all logs. 


## New dashboard page
Some kinda welcome page for something cute, Graphana may or may not be running so cannot assume it's going to be ready like we currently do.

**Comment by Velua** [comment]
- [ ] Rename BlockProducer name to NodeAccountName on the Join network flow. 

# Create Page
Radio boxes as part of the Create network wizard, 
Ask between dev and prod (difference is the TokenUsers package)
Ask between None governance and fractal democracy (disabled for now as we don't have it)
These questions compose the DataTables tick boxes determinine what gets installed.
The table is hidden by default and openable via a "Custom settings" accordion which displays a data table.
Unticking A will cause a dialog to ask confirmation that B and C is also lost as a consequence. 

# Join Page
- [ ] Connect to URL - Send a API request to check it's online and responding before moving to next page. 
- [ ] NodeAccountName

**Comment by James-Mart** [comment]
Misc feedback gathered while testing the latest update

### Boot wizard

- [ ] The Webmail package isn't selected by default when booting with development boot template, even though the Default package depends on it.
- [ ] Each page of the boot wizard should each have a title (like the "Installation Summary" title). (e.g. "Select Boot Template" and "Name Yourself")
- [ ] Could you add a little subtitle underneath the "Advanced" accordion that gives users an idea why certain packages are selected. Something like: "Selected packages correspond to selected boot template".
- [ ] When creating a block producer name, it says that the name must correspond to a valid psibase account name, but there's no validation of that. We can make it validate in real time that the specified name successfully roundtrips the Account name compression algo. 

### Post boot landing page

- [ ] The psibase icon in the nav bar should work with both light and dark mode
- [ ] Is the "Ram Usage" thing really talking about RAM? Who's RAM? Why does it say Firefox is consuming RAM even though Firefox isn't running on my pc or my node.

**Comment by swatanabe** [comment]
>     * [ ]  Is the "Ram Usage" thing really talking about RAM? Who's RAM? Why does it say Firefox is consuming RAM even though Firefox isn't running on my pc or my node.

It's a breakdown of physical RAM used by the `psinode` process (unrelated to any billing). "Firefox" (and "Edge") are just wrong labels.

**Comment by Velua** [comment]
>     * [ ]  The Webmail package isn't selected by default when booting with development boot template, even though the Default package depends on it.
> 

I believe this is just a side effect of cross contamination of build artifacts as I have this issue previously when messing with Brandons PR and has since left after doing an entirely fresh build. @James-Mart

**Comment by James-Mart** [comment]
> * [ ]  Rename BlockProducer name to NodeAccountName on the Join network flow.
> * [ ]  Connect to URL - Send a API request to check it's online and responding before moving to next page.

@Velua Were these completed?

**Comment by Velua** [comment]
Don't think so, I've raised  #829
