### ISSUE TITLE
Chainmail app v1

### ISSUE THREAD

**Issue by James-Mart** [gofractally/psibase#754]
# Description
An email client for sending private emails to other accounts.
Only supports a single receiver. Not intended for broadcasts. 

# Phased tasks

```[tasklist]
### Phase 1
- [x] Chainmail service: Initial skeleton ([PR](https://github.com/gofractally/psibase/pull/793))
- [x] Chainmail service: Support sending plaintext mail, emitting a corresponding event ([PR](https://github.com/gofractally/psibase/pull/793))
- [x] Chainmail service: Add http server with sent/received mail query support ([PR](https://github.com/gofractally/psibase/pull/793))
- [x] Chainmail plugin: Expose send action to UIs ([PR](https://github.com/gofractally/psibase/pull/793))
- [x] Chainmail UI: Connect UI with plugin and http server for functional chainmail MVP ([PR](https://github.com/gofractally/psibase/pull/798))
- [x] Send from accounts other than alice (Depends on [plugin storage](https://github.com/gofractally/psibase/pull/789)) #841
- [x] Use browser router instead of hash router #835
- [x] Support archiving mail (#821)
- [x] Support persisting mail (#855)
- [x] Dark mode #841
- [x] Empty UI states #841
```

**Comment by James-Mart** [comment]
CC @brandonfancher, consider updating this issue with any tasks that come out of the pr feedback

**Comment by James-Mart** [comment]
General note: 
It's probably better to focus on perfecting the experience / minimizing bugs with fewer features, than to add additional functionality.

**Comment by brandonfancher** [comment]
> General note: IMO, it's probably better to focus on perfecting the experience / minimizing bugs with fewer features, than to add additional functionality.

I'm definitely in alignment with that.

**Comment by James-Mart** [comment]
Closing - I opened a new issue to track future work
https://github.com/gofractally/psibase/issues/1064
