### ISSUE TITLE
Admin app improvements

### ISSUE THREAD

**Issue by James-Mart** [gofractally/psibase#828]
```[tasklist]
### Tasks
- [x] Add missing configurations, mainly for key management and TLS certificate management
- [x] Actually create the specified block producer account
- [x] Create key for bp account
```

**Comment by James-Mart** [comment]
Next round of X-Admin stuff was completed with https://github.com/gofractally/psibase/pull/1049
